#%RAML 1.0 NamedExample

value:
  -
    price: 100
    startDateTime: 2/12/2021
    address: address 1
    emptySeats: 50
    totalSeats: 100
    language: English

  -
    price: 200
    startDateTime: 3/12/2021
    address: address 2
    emptySeats: 100
    totalSeats: 150
    language: Hindi